---
tools:
  awscli: latest
  bitwarden-secrets-manager: latest
  dotnet: 9
  golang: latest
  gradle: 9
  helm: latest
  java: adoptopenjdk-25
  jq: latest
  k3d: latest
  kubectl: latest
  maven: latest
  nodejs: latest
  ollama: latest
  # python: 3.13.9 # still affected by https://github.com/asdf-community/asdf-python/issues/191 but asdf 0.19.0 might have the fix?
  rust: latest
  shellcheck: latest
  shfmt: latest
  sqlite: latest
  terraform: latest
